package tech.cursor.com.geez_dictionary.Entities

/**
 * id: Identifies word instantly! this will be autogenerated automatically by the room (autoincrement)
 * word: The Actual word
 * def: Word definitions
 * synonyms: word Synonyms
 * antonyms: word antonyms
 */
data class Word(val id: Int,val word: String,val def: String,val synonyms:String,val antonyms: String)